[package]
name = "azmq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
zmq-sys = { version = ">=0.12", default-features = false }
z85 = { version = ">=3.0.6", default-features = false }

num-traits = { version = ">=0.2.19", default-features = false }
bitflags = { version = ">=2.9", default-features = false, features = ["core"]}
derive_more = { version = ">=2.0", default-features = false, features = ["from", "debug", "display", "deref"]}
thiserror = { version = ">=2.0.12", default-features = false }
parking_lot = { version = ">=0.12.4", default-features = false, features = ["arc_lock"] }
async-trait = { version = ">=0.1.88", default-features = false }
futures = { version = ">=0.3.31", default-features = false, features = ["async-await", "alloc"]}

[lints]
workspace = true
